{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.namespaced | ternary "RoleBinding" "ClusterRoleBinding" }}
metadata:
  name: {{ include "kubernetes-event-exporter.fullname" . }}
  labels:
    {{- include "kubernetes-event-exporter.labels" . | nindent 4 }} 
  {{- if .Values.rbac.namespaced }}
  namespace: {{ include "kubernetes-event-exporter.namespace" . }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.rbac.namespaced | ternary "Role" "ClusterRole" }}
  name: {{ include "kubernetes-event-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    {{- if .Values.rbac.namespaced }}
    namespace: {{ include "kubernetes-event-exporter.namespace" . }}
    {{- end }}
    name: {{ include "kubernetes-event-exporter.fullname" . }}
{{- end }}
